# Generated by Django 3.2.23 on 2023-12-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20231208_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='listing_currency',
            field=models.IntegerField(choices=[(0, '£'), (1, '$'), (2, '€'), (3, '¥'), (4, '₩'), (5, '₺'), (6, '₣'), (7, '₹'), (8, 'د.ك')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='listing_timespan',
            field=models.IntegerField(choices=[(0, 'p/w'), (1, 'p/m')], default=1),
        ),
    ]
