# Generated by Django 3.2.23 on 2023-12-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20231208_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='listing_currency',
            field=models.CharField(choices=[('£', 'GBP'), ('$', 'USD'), ('€', 'Euro'), ('¥', 'Yen'), ('₩', 'Won'), ('₺', 'Lira'), ('₣', 'Franc'), ('₹', 'Rupee'), ('د.ك', 'Dinar')], default='GBP', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='listing_timespan',
            field=models.CharField(choices=[('p/w', 'per week'), ('p/m', 'per month')], default='per month', max_length=100),
        ),
    ]
