# Generated by Django 3.2.23 on 2023-12-12 18:04

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0005_auto_20231208_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('excerpt', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('listing_price', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]')])),
                ('listing_currency', models.CharField(choices=[('£', 'GBP'), ('$', 'USD'), ('€', 'Euro'), ('¥', 'Yen'), ('₩', 'Won'), ('₺', 'Lira'), ('₣', 'Franc'), ('₹', 'Rupee'), ('د.ك', 'Dinar')], default='GBP', max_length=100)),
                ('listing_timespan', models.CharField(choices=[('p/w', 'per week'), ('p/m', 'per month')], default='per month', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geek_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
