# Generated by Django 3.2.23 on 2024-04-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20231213_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
